version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip3 install --upgrade pip
      - aws codeartifact login --tool twine --repository personal-repo --domain personal --domain-owner 972734064061
      - pip3 install -r requirements.txt
      - pip3 install .
      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      - pytest 
        --html=test-reports/report.html 
        --self-contained-html
        -s
        -v
        --cov 
        --cov=dspt
        --cov-report=html:test-reports/coverage 
        --cov-report=xml:test-reports/coverage.xml
        --junitxml=test-reports/junit.xml 
        --log-file=test-reports/logs.txt 
        tests
      - cd docs && make clean html && cd -
      - aws s3 sync ./docs/_build/html s3://superbucket42/package-docs/l2-orderbook-tops/latest
      - twine upload --repository personal-repo l2-orderbook-tops
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  CoverageReports:
    files:
      - 'coverage.xml' 
    discard-paths: yes
    file-format: 'COBERTURAXML'
    base-directory: 'test-reports'
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml
